language: c

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libmodule-find-perl libfile-slurp-perl libfile-which-perl libmime-lite-perl

install:
 - ./configure --prefix=$(pwd)/build
 - make && make install

script:
 - perl -Iperl/lib imvirt
 - sudo perl -Iperl/lib imvirt
 - sudo perl -Iperl/lib imvirt-report -s /dev/stdout
